[general]
live_config_reload = true

# [env]

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#565656"
blue = "#49a4f8"
cyan = "#99faf2"
green = "#c0e17d"
magenta = "#a47de9"
red = "#ec5357"
white = "#ffffff"
yellow = "#f9da6a"

[colors.normal]
black = "#2e2e2e"
blue = "#47a0f3"
cyan = "#64dbed"
green = "#abe047"
magenta = "#7b5cb0"
red = "#eb4129"
white = "#e5e9f0"
yellow = "#f6c744"

[colors.primary]
background = "#101421"
foreground = "#fffbf6"

[cursor]
style.shape = "Block"          # "Block" | "Underline" | "Beam"
style.blinking = "On"          # "Never" | "Off" | "On" | "Always"
blink_interval = 750
vi_mode_style.shape = "Block"
vi_mode_style.blinking = "Off"

[env]
TERM = "alacritty"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 5000
multiplier = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless" # "Full" | "None" | "Transparent" | "Buttonless"
dynamic_padding = true
opacity = 0.1
blur = true
startup_mode = "Windowed"  # "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
title = "Alacritty"
dynamic_title = true
resize_increments = true
# NOTE: These options are only available on macOS
option_as_alt = "OnlyLeft" # "OnlyLeft" | "OnlyRight" | "Both" | "None"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 130
lines = 35

[window.padding]
x = 10
y = 0
