tap "netbirdio/tap"

brew "bash-completion"
brew "bat"
brew "cowsay"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gnupg"
brew "graphviz"
brew "iproute2mac"
brew "lsd"
brew "lynx"
brew "pstree"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "wget"
brew "zoxide"
brew "zsh"
brew "netbirdio/tap/netbird"

cask "alacritty"
cask "font-jetbrains-mono-nerd-font"
cask "netbird-ui"
