[general]
live_config_reload = true

# --- Dracula Theme Start ---

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"
dim_foreground = "#6272a4"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#282a36"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]
text = "#282a36"
cursor = "#8be9fd"

[colors.search.matches]
foreground = "#f8f8f2"
background = "#44475a"

[colors.search.focused_match]
foreground = "#282a36"
background = "#ffb86c"

[colors.footer_bar]
foreground = "#f8f8f2"
background = "#44475a"

[colors.hints.start]
foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]
foreground = "#f8f8f2"
background = "#44475a"

[colors.selection]
text = "#f8f8f2"
background = "#44475a"

[colors.normal]
black = "#000000"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#bbbbbb"

[colors.bright]
black = "#555555"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#caa9fa"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#ffb86c"

[[colors.indexed_colors]]
index = 17
color = "#ff5555"

# --- Dracula Theme End ---

[cursor]
style.shape = "Block"
style.blinking = "On"
blink_interval = 750
vi_mode_style.shape = "Block"
vi_mode_style.blinking = "Off"

[env]
TERM = "alacritty"

[font]
size = 17

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 10000
multiplier = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.9
blur = true
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
resize_increments = true
# NOTE: These options are only available on macOS
option_as_alt = "OnlyLeft"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 130
lines = 35

[window.padding]
x = 0
y = 10
