[general]
import = ["~/.cache/system-theme/alacritty.toml"]
live_config_reload = true

[cursor]
style.shape = "Block"
style.blinking = "On"
blink_interval = 750
vi_mode_style.shape = "Block"
vi_mode_style.blinking = "Off"

[env]
TERM = "alacritty"

[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 10000
multiplier = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 1
blur = true
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
resize_increments = true
# NOTE: These options are only available on macOS
option_as_alt = "OnlyLeft"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 130
lines = 35

[window.padding]
x = 0
y = 10
