name: Auto Update Submodules

on:
  workflow_dispatch: # Allows manual triggering from source repo lelouvincx/nvim
  schedule: # Optional: Schedule the action
    - cron: "0 0 1 * *" # Runs every month at midnight

jobs:
  update-submodules:
    name: "Update Submodules"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive # Ensures submodules are checked out

      # Step 2: Update Submodules
      - name: Update Submodules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token to authenticate
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '159746302+ubunchuu-admin@users.noreply.github.com'
          git pull --recurse-submodules
          git submodule update --remote --recursive

      # Step 3: Push Changes (if any)
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token to authenticate
        run: |
          git add .
          git commit -am "auto(nvim): update latest nvim submodule" || echo "No changes to commit"
          git push origin HEAD
